test
tonlabs/TON-Surf-Localization pull request #25
Opened 2021-09-16 12:07 UTC by AnnStepanova

2021-09-16 13:49 UTC, AleksandrHorev approved these changes

2021-09-16 13:50 UTC, AleksandrHorev commented
@AnnStepanova please review

2021-09-21 08:05 UTC, BigRoma commented on README-ru.md
> +  В [веб-приложении TON-Surf](https://beta.ton.surf/accounts) есть помощник локализатора - он показывает полный путь до нужной строчки при наведении на неё.
I think you don't need **accounts** at the end.

2021-09-22 08:58 UTC, AleksandrHorev commented
@AnnStepanova @AleksandrHorev @TvidL-oss

2021-09-22 09:01 UTC, AleksandrHorev approved these changes

2021-09-22 14:25 UTC, BigRoma requested changes
Please fix the link and we can merge it.

2021-09-22 14:30 UTC, BigRoma approved these changes

2021-09-22 14:31 UTC, merged