Lokalise: Translations update
tonlabs/TON-Surf-Localization pull request #8
Opened 2021-08-25 14:21 UTC by localized26

This pull request was initiated by Lokalise (user Roman Tishakov) at 2021-08-25 16:21:48

2021-08-26 07:41 UTC, BigRoma commented on src/ko.json
> +        "disableAutoresume": "Auto-resume 기능 끄기",
@kkkhesha Check this translation

2021-08-26 07:41 UTC, BigRoma commented on src/ko.json
> +            "autoresumeFee": "Auto-resume 수수료",
@kkkhesha And this

2021-08-26 08:27 UTC, AnnBoo commented on src/ru.json
> +                    "failedToSaveFavorite": "Не удалось сохранить любимый статус. Повторите попытку позже"
любимый статус - это точно корректная формулировка?

2021-08-26 08:27 UTC, AnnBoo commented on src/ru.json
> +        "restoreHint": "Вы можете восстановить кошелек, созданный только в Surf",
Переведено не полностью: 
```suggestion
        "restoreHint": "В настоящее время поддерживается только восстановление кошельков, созданных в Surf.",
```

2021-08-26 13:10 UTC, BigRoma commented on src/ru.json
> +                    "failedToSaveFavorite": "Не удалось сохранить любимый статус. Повторите попытку позже"
```suggestion
                    "failedToSaveFavorite": "Не удалось обновить статус. Повторите попытку позже"
```

2021-08-26 13:17 UTC, BigRoma approved these changes

2021-08-26 14:37 UTC, AnnBoo approved these changes

2021-08-26 14:38 UTC, AnnBoo approved these changes

2021-08-27 07:51 UTC, sertony requested changes

2021-08-27 07:51 UTC, sertony commented on src/en.json
> +        "nightTheme": {
This was removed in Surf

2021-08-27 07:53 UTC, sertony requested changes

2021-08-27 07:53 UTC, sertony commented on src/en.json
> +            "tokens": "Tokens"
Oh, this was also removed

2021-08-27 07:54 UTC, sertony approved these changes
Discussed that left comments will be resolved once development is synced with lokalise.com

2021-08-27 07:54 UTC, merged